global {
  gForce = -9.8
  dragCoefficient = 0.0
  bullet42mm = false
}
camera {
  type = "DahengDriver"
  openMode = "SerialNumber"
  identifier = "NE0200080111"
  fps = 30
  fov = 41
  exposureTime = 0.001
  binning = 0
  width = 1920
  height = 1200
  image_frame_atom = ["server","calibrator"]
}
calibrator {
  type = "UndistortCalibrator"
  boardSizeWidth = 8
  boardSizeHeight = 6
  squareSize = 25
  flipVertical = false
  nrFrames = 25
  aspectRatio = 1
  calibZeroTangentDist = true
  calibFixPrincipalPoint = true
  outputFileName = "cameraCalibrator.xml"
  writePoints = true
  writeExtrinsics = true
  writeGrid = true
  showUndistorted = true
  fixK1 = false
  fixK2 = false
  fixK3 = false
  fixK4 = true
  fixK5 = true
  winSize = 11
  image_frame_atom = ["server"]
}
server {
  type = "HttpServer"
}