stages:
  - build
  - test
  - deploy

build-job-windows:
  stage: build
  script:
    - cmake -G "Visual Studio 16 2019" -A x64 -B ./build -DARTINX_HUB_CAMERA=USB3 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:/WorkSpace/SDKS/vcpkg/scripts/buildsystems/vcpkg.cmake
    - cmake --build ./build --config Release
  rules:
    - if: $DEPLOY_TARGET == null
  cache:
    key: $CI_COMMIT_SHA
    paths:
      - build/*

build-job-linux:
  stage: build
  script:
    - cmake -A x64 -B ./build -DARTINX_HUB_CAMERA=$CAMERA_TYPE -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=~/workspace/package/vcpkg/scripts/buildsystems/vcpkg.cmake
    - cmake --build ./build --config Release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $DEPLOY_TARGET != null
  cache:
    key: $CI_COMMIT_SHA
    paths:
      - build/*

test-job:
  stage: test
  script:
    - cd build
    - ctest --build-config Release -j 8
  artifacts:
    name: "report"
    paths:
      - ./build/testResult.log
    expire_in: 1 month
    expose_as: "test report"
  rules:
    - if: $DEPLOY_TARGET == null
  cache:
    key: $CI_COMMIT_SHA

deploy-job:
  stage: deploy
  script:
    - sudo python3 ./scripts/setup-service $CI_RUNNER_TAGS
  environment:
    name: $DEPLOY_TARGET
    on_stop: stop-service
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $DEPLOY_TARGET != null
      when: manual
  cache:
    key: $CI_COMMIT_SHA

stop-service:
  stage: deploy
  script:
    - sudo python3 ./scripts/teardown-service.py
  when: manual
  environment:
    name: $DEPLOY_TARGET
    action: stop
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $DEPLOY_TARGET != null
      when: manual
  cache:
    key: $CI_COMMIT_SHA
