stages:
  - build-test
  - deploy

build-test-job:
  stage: build-test
  script:
    - cmake -G "Visual Studio 16 2019" -A x64 -B ./build -DARTINX_HUB_CAMERA=USB3 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:/WorkSpace/SDKS/vcpkg/scripts/buildsystems/vcpkg.cmake
    - cmake --build ./build --config Release
    - cd build
    - ctest --build-config Release -j 8
  artifacts:
    when: always
    name: "report"
    paths:
      - ./build/testResult.log
    expire_in: 1 month
    expose_as: "test report"

deploy_infantry:
  stage: deploy
  script:
    - echo "Deploy to infantry"
  environment:
    name: Infantry
    url: 
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
