cmake_minimum_required (VERSION 3.19)

project(artinx_hub)
set(CMAKE_CXX_STANDARD 17)
enable_testing()

if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
	add_compile_definitions("UNICODE")
	add_compile_definitions("_UNICODE")
	add_compile_options("/utf-8")
	if(CMAKE_BUILD_TYPE MATCHES Debug)
		add_compile_options("/Od" "/Oy-")
	else()
		add_compile_options("/O2" "/Ob2" "/Oi" "/Ot" "/Oy" "/GT" "/GL" "/Qpar")
		add_link_options("/LTCG:incremental" "/OPT:REF" "/OPT:ICF")
	endif()
elseif(CMAKE_COMPILER_IS_GNUCXX)
	if(CMAKE_BUILD_TYPE MATCHES Debug)
		add_compile_options("-O0" "-fno-omit-frame-pointer")
	else()
		add_compile_options("-O3")
	endif()
endif()

if(CMAKE_BUILD_TYPE MATCHES Debug)
	add_compile_definitions("ARTINXHUB_DEBUG")
endif()

include_directories(BEFORE include)

add_subdirectory(src)
add_subdirectory(tests)
