global {
#     gForce = -9.8 # General
    gForce = -9.7949 # Nanjing(near to Changzhou)
#     gForce = -9.7833 # Guangzhou(near to Shenzhen)
    dragCoefficient = 0.0
    bullet42mm = false
}

server_up {
    type = "HttpServer"
}
camera_up {
    type = "DahengDriver"
    openMode = "Index"
    identifier = 1
    fps = 210.0
    fov = 48.0
    #fov = 23.0
    exposureTime = 0.001
    dx = -0.06
    dy = 0.05
    dz = -0.06
    image_frame_atom = ["detector_up","server_up"]
}

detector_up {
    type = "FakeCarDetector"
    car_detect_available_atom = ["armor_detector_up"]
}

armor_detector_up {
    type = "ArmorDetector"
    isRed = true
    globalScale = 1.0
    thresholdForBlue = [120,256,256]
    thresholdForRed = [40,256,256]
    maxAreaRatio = 2.0
    maxLightAngle = 0.3
    maxLightRectRatio = 10.0
    maxArmorRectRatio = 0.5
    maxArmorAngle = 0.8
    minLightBaseAngle = 0.3
    maxParallelAngle = 0.7
    minLightHeightRatio = 0.6
    armor_detect_available_atom = ["armor_locator_up", "drawer_up"]
    image_frame_atom = ["server_up"]
}

drawer_up {
    type = "ArmorDetectorDrawer"
    image_frame_atom = ["server_up"]
}

armor_locator_up {
    type = "ArmorLocator"
    detect_available_atom = ["strategy_up"]
}

strategy_up {
    type = "SentryStrategy"
    distanceThreshold = 0.0
    set_target_atom = ["solver_up"]
}

solver_up {
    type = "AngleSolver"
    precision = 0.001
    delay = 0.2
    set_target_info_atom = ["serial"]
}

server_down {
    type = "HttpServer"
}
camera_down {
    type = "DahengDriver"
    openMode = "Index"
    identifier = 1
    fps = 210.0
    fov = 48.0
    #fov = 23.0
    exposureTime = 0.001
    dx = -0.06
    dy = 0.05
    dz = -0.06
    image_frame_atom = ["detector_down","server_down"]
}

detector_down {
    type = "FakeCarDetector"
    car_detect_available_atom = ["armor_detector_down"]
}

armor_detector_down {
    type = "ArmorDetector"
    isRed = true
    globalScale = 1.0
    thresholdForBlue = [120,256,256]
    thresholdForRed = [40,256,256]
    maxAreaRatio = 2.0
    maxLightAngle = 0.3
    maxLightRectRatio = 10.0
    maxArmorRectRatio = 0.5
    maxArmorAngle = 0.8
    minLightBaseAngle = 0.3
    maxParallelAngle = 0.7
    minLightHeightRatio = 0.6
    armor_detect_available_atom = ["armor_locator_down", "drawer_down"]
    image_frame_atom = ["server_down"]
}

drawer_down {
    type = "ArmorDetectorDrawer"
    image_frame_atom = ["server_down"]
}

armor_locator_down {
    type = "ArmorLocator"
    detect_available_atom = ["strategy_down"]
}

strategy_down {
    type = "SentryStrategy"
    distanceThreshold = 0.0
    set_target_atom = ["solver_down"]
}

solver_down {
    type = "AngleSolver"
    precision = 0.001
    delay = 0.2
    set_target_info_atom = ["serial"]
}

# todo(@fro1ster): how do sentry serial receive 2 commands in one serial port? do we need a new serial class for sentry? or a new behavior?
serial {
    type = "SerialPort"
    devPath = "/dev/ttyUSB0"
    baudRate = 921600
    headHeightOffset = 0.0
    update_head_atom = ["solver"]
    update_posture_atom = ["solver"]
}
