global {
#     gForce = -9.8 # General
#    gForce = -9.7949 # Nanjing(near to Changzhou)
     gForce = -9.7833 # Guangzhou(near to Shenzhen)
    dragCoefficient = 0.0
    bullet42mm = false
}

camera {
    type = "DahengDriver"
    openMode = "Index"
    identifier = "1"
    cameraName = "Camera"
    enableAutoWhiteBalance = true
    fps = 150
    fov = 30.0
    flip = false
    gain = 12.0
    exposureTime = 0.004
    dy = 0.03 # TODO
    dx = 0.0 # TODO
    yaw = -0.5
    pitch = -1.0 #degree
    image_frame_atom = ["armor_detector", "recorder","server"]
    # image_frame_atom = ["rune_detector", "recorder", "server"]
    # image_frame_atom = ["rune_detector", "server"]
}

armor_detector {
    type = "ArmorDetector"
    debugView = false
    binaryThresh = 60
    minLightRectRatio = 0.1   # width/height
    maxLightRectRatio = 0.6   # width/height
    maxLightAngle = 20.0       # angle(degree)
    min2lightLenRatio = 0.6   # light1.height / light2.height
    max2LightDiffAngle = 20.0
    minArmorRectRatio = 0.8   # width/height
    maxArmorRectRatio = 8.0   # width/height
    maxArmorAngle = 30       # angle(degree)
    minLargeArmorRatio = 3.2  # width / height
    numClassifyModelPath = "data/weights/armor_classify/mlp.onnx"
    numProbThresh = 0.8
    armor_detect_available_atom = ["drawer"]
    image_frame_atom = ["server"]
}

recorder {
  type = "VideoRecorder"
  base = "record"
  segmentLength = 30.0
  fps = 60.0
}

server {
  type = "HttpServer"
}

drawer {
  type = "ArmorDetectorDrawer"
  image_frame_atom = ["server"]
}
