global {
#     gForce = -9.8 # General
    gForce = -9.7949 # Nanjing(near to Changzhou)
#     gForce = -9.7833 # Guangzhou(near to Shenzhen)
    dragCoefficient = 0.0
    bullet42mm = false
}

camera {
    type = "DahengDriver"
    openMode = "Index"
    identifier = 1
    fps = 210.0
    fov = 30.0
    exposureTime = 0.005
    enableAutoWhiteBalance = true
    dy = 0.05 # TODO
    dz = -0.06 # TODO
    image_frame_atom = ["energy_detector","server","recorder"]
}

energy_detector {
    type = "EnergyDetector"
    binaryThreshold = 40
    vaneLength = 1.2
    energy_detect_available_atom = ["strategy"]
    image_frame_atom = ["server"]
}

strategy {
    type = "InfantryStrategy"
    update_roi_atom = ["energy_detector"]
}

server {
    type = "HttpServer"
}