global {
  # gForce = -9.8 # General
    gForce = -9.7949 # Nanjing(near to Changzhou)
  # gForce = -9.7833 # Guangzhou(near to Shenzhen)
    dragCoefficient = 0.0
    bullet42mm = false
    isRed = true
}

source {
    type = "VideoReplay"
    path = "/home/artinx-008/workspace/codes/artinx-hub/record/22_22_16.mkv"
    fps = 30.0
    fov = 30.0
    width = 1440
    height = 1280
    image_frame_atom = ["armor_detector", "server"]
}


armor_detector {
    type = "ArmorDetector"
    debugView = true
    binaryThresh = 70
    minLightRectRatio = 0.1   # width/height
    maxLightRectRatio = 0.6   # width/height
    maxLightAngle = 20.0       # angle(degree)
    min2lightLenRatio = 0.6   # light1.height / light2.height
    max2LightDiffAngle = 20.0
    minArmorRectRatio = 0.8   # width/height
    maxArmorRectRatio = 8.0   # width/height
    maxArmorAngle = 30       # angle(degree)
    minLargeArmorRatio = 3.2  # width / height
    numClassifyModelPath = "data/weights/armor_classify/mlp.onnx"
    numProbThresh = 0.8
    armor_detect_available_atom = ["armor_locator", "drawer"]
    image_frame_atom = ["server"]
}

drawer {
    type = "ArmorDetectorDrawer"
    image_frame_atom = ["server"]
}

server {
    type = "HttpServer"
}


