global {
    gForce = -9.7949 # Nanjing(near to Changzhou)
    dragCoefficient = 0.0
    bullet42mm = false
    isRed = false
}

source {
   type = "VideoReplay"
   path = "/home/lzh/Downloads/round1/1682156478.mp4"
   fps = 30
   fov = 30.0
   width = 640
   height = 480
   image_frame_atom = ["armor_detector", "server"]
}

# source {
#     type = "ImageSequenceReplay"
#     path = <>
#     extension = "png"
#     fps = 1
#     fov = 30.0
#     width = 640
#     height = 360
#     binaryThresh = 240
#     image_frame_atom = ["armor_detector", "server"]
# }

# camera {
#     type = "DahengDriver"
#     openMode = "Index"
#     identifier = 1
#     fps = 210.0
#     fov = 30.0
#     exposureTime = 0.005
#     dy = 0.05 # TODO
#     dz = -0.06 # TODO
#     image_frame_atom = ["armor_detector","server"]
# }


armor_detector {
    type = "ArmorDetector"
    debugView = false
    binaryThresh = 100
    minLightRectRatio = 0.1   # width/height
    maxLightRectRatio = 0.6   # width/height
    maxLightAngle = 5.0       # angle(degree)
    max2LightDiffAngle = 8.0  # max 2 lights diff angle
    min2lightLenRatio = 0.6   # light1.height / light2.height
    minArmorRectRatio = 0.8   # width/height
    maxArmorRectRatio = 5.0   # width/height
    maxArmorAngle = 10       # angle(degree)
    minLargeArmorRatio = 3.2  # width / height
    numClassifyModelPath = "data/weights/armor_classify/cls_num.onnx"
    numProbThresh = 0.7
    armor_detect_available_atom = ["drawer"]
    image_frame_atom = ["server"]
}

# armor_detector {
#     type = "NNetArmorDetector"
#     networkPath = "data/weights/armor_detect/opt-0625-001.onnx"  #network training file path
#     inputWidth = 416
#     inputHeight = 416
#     numClasses = 8 #Number of classes
#     numColors = 4  #Number of color
#     bboxConfThresh = 0.6
#     topK = 128
#     nmsThresh = 0.01
#     fftConfError = 0.15
#     fftMinIou = 0.9
#     maxArmorRatio = 4.0
#     maxBarAngleDiff = 15.0
#     armor_nnet_detect_available_atom = ["drawer"]
#     image_frame_atom = ["server"]
# }

drawer {
    type = "ArmorDetectorDrawer"
    image_frame_atom = ["server"]
}


server {
    type = "HttpServer"
}

