global {
  # gForce = -9.8 # General
    gForce = -9.7949 # Nanjing(near to Changzhou)
  # gForce = -9.7833 # Guangzhou(near to Shenzhen)
    dragCoefficient = 0.0
    bullet42mm = false
    isRed = true
}

source {
    type = "VideoReplay"
    path="/home/lambillda/Videos/5.25/CENTER"
    fps = 60.0
    fov = 30.0
    width = 1920
    height = 1200
    image_frame_atom = ["server"]
}

server {
    type = "HttpServer"
}
