global {
  gForce = -9.8
  dragCoefficient = 0.0
  bullet42mm = false
}

source {
    type = "VideoReplay"
    path = "/home/artinx-003/Desktop/record/test5.mp4"
    fps = 20.0
    fov = 30.0
    width = 656
    height = 492
    image_frame_atom = ["detector"]
}

detector {
    type = "FakeCarDetector"
    car_detect_available_atom = ["armor_detector"]
}

armor_detector {
    type = "ArmorDetector"
    globalScale = 1.0
    thresholdForBlue = [120,256,256]
    thresholdForRed = [40,256,256]
    maxAreaRatio = 2.0
    maxLightAngle = 0.3
    maxLightRectRatio = 10.0
    maxArmorRectRatio = 0.5
    maxArmorAngle = 0.8
    minLightBaseAngle = 0.3
    maxParallelAngle = 0.2
    minLightHeightRatio = 0.6
    armor_detect_available_atom = ["drawer"]
    image_frame_atom = ["server"]
}

drawer {
    type = "ArmorDetectorDrawer"
    image_frame_atom = ["server"]
}

server {
  type = "HttpServer"
}
