global {
#   gForce = -9.8 # General
  gForce = -9.7949 # Nanjing(near to Changzhou)
#   gForce = -9.7833 # Guangzhou(near to Shenzhen)
  dragCoefficient = 0.0
  bullet42mm = true
  defaultBulletSpeed = 13.6
}

# source {
#     type = "VideoReplay"
#     path = "/home/lzh/Downloads/video_test/RED_6/test2.mp4"
#     fps = 100
#     fov = 30.0
#     width = 640
#     height = 480
#     image_frame_atom = ["armor_detector"]
# }

camera {
  type = "DahengDriver"
  openMode = "Index"
  identifier = 1
  fps = 210.0
  fov = 30.0
  exposureTime = 0.00375
  gain = 15

  dx = 0.0 # TODO
  dy = 0.106245 # TODO
  dz = -0.11773 # TODO
#   yaw = 0
  pitch = -18.05 #TODO

  enableAutoWhiteBalance = true
  image_frame_atom = ["armor_detector","recorder"]
}

serial {
  type = "SerialPort"
  devPath = "/dev/ttyUSB0"
  baudRate = 921600
  minBulletSpeed = 7.0
  maxBulletSpeed = 16.0
  # enableEnergyControl = true
  # energy_detector_control_atom = ["strategy","energy_detector"]
  update_head_atom = ["camera"]
  update_posture_atom = ["predictor"]
  hero_strategy_control_atom = ["strategy","periodSolver"]
}

armor_detector {
  type = "ArmorDetector"
  debugView = false
  binaryThresh = 60
  minLightRectRatio = 0.1   # width/height
  maxLightRectRatio = 0.6   # width/height
  maxLightAngle = 30.0       # angle(degree)
  min2lightLenRatio = 0.6   # light1.height / light2.height
  max2LightDiffAngle = 10.0
  minArmorRectRatio = 0.8   # width/height
  maxArmorRectRatio = 5.0   # width/height
  maxArmorAngle = 30       # angle(degree)
  minLargeArmorRatio = 3.2  # width / height
  numClassifyModelPath = "data/weights/armor_classify/mlp.onnx"
  numProbThresh = 0.7
  armor_detect_available_atom = ["armor_locator"]
  image_frame_atom = []
}

armor_locator {
  type = "ArmorLocator"
  largeArmor = [1,7]
  detect_available_atom = ["strategy"]
}

strategy {
  type = "HeroStrategy"
  staticImgPosThreshold = 2
  priorList = [6,7,0]
  set_target_atom = ["predictor"]
  set_period_target_atom = ["periodPredictor"]
  set_period_outpost_atom = ["periodOutpostPredictor"]
}

predictor {
  type = "CarPredictor"
  enablePredictor = false
  maxMatchDist = 0.4
  maxMatchYaw = 0.2
  trackingThreshold = 5
  lostThreshold = 50
      #xc    yc    zc    yaw   vxc   vyc   vzc   vyaw  r
  Q = [1e-2, 2e-3, 1e-2, 4e-3, 4e-2, 4e-4, 4e-2, 2e-2, 0.0016]
      #xa      ya      za     yaw
  R = [0.0006, 0.0006, 0.006, 0.0018]
  car_predict_atom = ["solver"]
}

periodPredictor{
  type = "PeriodPredictor"
  period_predict_success_atom = ["periodSolver"]
}

periodOutpostPredictor{
  type = "PeriodOutpostPredictor"
  period_predict_success_atom = ["periodSolver"]
}

solver {
  type = "AngleSolver"
  delay = 0.0
  set_target_info_atom = ["serial"]
}

periodSolver {
  type = "PeriodSolver"
  delay = 0.02
  headDelay = 0.1
  set_target_info_atom = ["serial"]
}

recorder {
  type = "VideoRecorder"
  base = "record"
  segmentLength = 15.0
  fps = 60.0
}
