global {
#   gForce = -9.8 # General
  gForce = -9.7949 # Nanjing(near to Changzhou)
#   gForce = -9.7833 # Guangzhou(near to Shenzhen)
  dragCoefficient = 0.0
  bullet42mm = true
  initBulletSpeed = 8.5
}

# source {
#     type = "VideoReplay"
#     path = "/home/lzh/Downloads/video_test/RED_6/test2.mp4"
#     fps = 100
#     fov = 30.0
#     width = 640
#     height = 480
#     image_frame_atom = ["armor_detector"]
# }

camera {
  type = "DahengDriver"
  openMode = "Index"
  identifier = 1
  fps = 210.0
  fov = 30.0
  exposureTime = 0.0005

  dx = 0.056 # TODO
  dy = 0.065 # TODO
  dz = -0.130224 # TODO
  pitch = -20 #TODO

#   dx = 0 #TODO
#   dy = 0.0695 #TODO
#   dz = -0.09445 #TODO
#   pitch = 0 #TODO

  enableAutoWhiteBalance = true
  image_frame_atom = ["armor_detector","server","recorder"]
#  image_frame_atom = ["armor_detector","server"]
}

armor_detector {
    type = "ArmorDetector"
    debugView = false
    binaryThresh = 100
    maxLightLen = 200
    minLightRectRatio = 0.1   # width/height
    maxLightRectRatio = 0.6   # width/height
    maxLightAngle = 5.0       # angle(degree)
    min2lightLenRatio = 0.6   # light1.height / light2.height
    minArmorRectRatio = 0.8   # width/height
    maxArmorRectRatio = 5.0   # width/height
    maxArmorAngle = 15       # angle(degree)
    minLargeArmorRatio = 3.2  # width / height
    numClassifyModelPath = "data/weights/armor_classify/cls_num.onnx"
    numProbThresh = 0.6
    armor_detect_available_atom = ["armor_locator", "drawer"]
    image_frame_atom = ["server"]
}

# armor_detector {
#     type = "NNetArmorDetector"
#     networkPath = "data/weights/armor_detect/opt-0625-001.onnx"  #network training file path
#     inputWidth = 416
#     inputHeight = 416
#     numClasses = 8 #Number of classes
#     numColors = 4  #Number of color
#     bboxConfThresh = 0.65
#     topK = 128
#     nmsThresh = 0.3
#     fftConfError = 0.15
#     fftMinIou = 0.9
#     armor_nnet_detect_available_atom = ["drawer", "armor_locator"]
#     image_frame_atom = ["server"]
# }


armor_locator {
  type = "ArmorLocator"
  largeArmor = [1,7]
  detect_available_atom = ["strategy"]
}

predictor {
  type = "CarPredictor"
  enablePredictor = true
  maxMatchDistance = 0.2
  trackingThreshold = 5
  lostThreshold = 50
      #xc    yc    zc    yaw   vxc   vyc   vzc   vyaw  r
  Q = [1e-2, 1e-2, 1e-2, 2e-2, 0.005, 1e-4, 0.005, 4e-2, 1e-3]
      #xa    ya    za    yaw
  R = [0.0009, 0.0009, 0.0025, 0.0036]
  predict_success_atom = ["solver"]
}
periodPredictor{
  type = "PeriodPredictor"
  period_predict_success_atom = ["periodSolver"]
}
periodOutpostPredictor{
  type = "PeriodOutpostPredictor"
  period_predict_success_atom = ["periodSolver"]
}
solver {
  type = "AngleSolver"
  delay = 0.0
  set_target_info_atom = ["serial"]
}
periodSolver {
  type = "PeriodSolver"
  precision = 0.007
  delay = 0.015
  set_target_info_atom = ["serial"]
  headDelay = 0.1
}
strategy {
  type = "HeroStrategy"
  periodPredictType = "outpost"
  set_target_atom = ["predictor"]
  set_period_target_atom = ["periodPredictor"]
  set_period_outpost_atom = ["periodOutpostPredictor"]
}

serial {
  type = "SerialPort"
  devPath = "/dev/ttyUSB0"
  baudRate = 921600
  minBulletSpeed = 7.0
  maxBulletSpeed = 16.0
  # enableEnergyControl = true
  # energy_detector_control_atom = ["strategy","energy_detector"]
  getBulletSpeedFromSerial = true
  getOutpostModeFromSerial = true
  getShootDelayFromSerial = true
  update_head_atom = ["camera"]
  update_posture_atom = ["predictor"]
  outpost_detector_control_atom = ["strategy","periodSolver"]
}

server {
  type = "HttpServer"
}

drawer {
  type = "ArmorDetectorDrawer"
  image_frame_atom = ["server"]
}

recorder {
  type = "VideoRecorder"
  base = "record"
  segmentLength = 15.0
  fps = 60.0
}

server {
  type = "HttpServer"
}