global {
#     gForce = -9.8 # General
    gForce = -9.7949 # Nanjing(near to Changzhou)
#     gForce = -9.7833 # Guangzhou(near to Shenzhen)
    dragCoefficient = 0.0
    bullet42mm = false
}

server {
    type = "HttpServer"
    ethName = "eth0"
}

camera {
    type = "DahengDriver"
    openMode = "Index"
    identifier = 1
    fps = 210.0
    fov = 30.0
    enableAutoWhiteBalance = true
    exposureTime = 0.0035
    dy = 0.096 # TODO
    dz = -0.0
    yaw = 0
    pitch = 0
    gain = 10
    flip = false
    image_frame_atom = ["armor_detector", "server"]
}

# source {
#     type = "VideoReplay"
#     path = "/home/artinx009/record/red.mp4"
#     fps = 60
#     fov = 30.0
#     width = 640
#     height = 480
#     image_frame_atom = ["armor_detector", "server"]
# }

armor_detector {
    type = "ArmorDetector"
    debugView = false
    binaryThresh = 100                                                      
    minLightRectRatio = 0.1   # width/height
    maxLightRectRatio = 0.6   # width/height
    maxLightAngle = 30.0       # angle(degree)
    min2lightLenRatio = 0.6   # light1.height / light2.height
    max2LightDiffAngle = 7.0
    minArmorRectRatio = 0.8   # width/height
    maxArmorRectRatio = 11.0   # width/height
    maxArmorAngle = 20       # angle(degree)
    minLargeArmorRatio = 3.2  # width / height
    numClassifyModelPath = "/home/artinx/workspace/artinx-hub/data/weights/armor_classify/mlp.onnx"
    numProbThresh = 0.7
    armor_detect_available_atom = ["drawer", "armor_locator"]
    # armor_detect_available_atom = ["drawer"]

    image_frame_atom = ["server"]
}

drawer {
    type = "ArmorDetectorDrawer"
    image_frame_atom = ["server"]
}

armor_locator {
    type = "ArmorLocator"
    largeArmor = [1]
    detect_available_atom = ["strategy"]
}

strategy {
    type = "InfantryStrategy"
    set_target_atom = ["predictor"]
}


predictor {
  type = "CarPredictor"
  enablePredictor = true
  maxMatchDist = 0.20
  trackingThreshold = 5
  lostThreshold = 50
  maxMatchYaw = 0.8
  sigma2Qxyz = 20
  sigma2Qyaw = 100
  sigma2QR = 800
  Rxyz = 0.05
  Ryaw = 0.1
  car_predict_atom = ["solver"]
}

solver {
    type = "AngleSolver"
    delay = 0.08
    set_target_info_atom = ["serial"]
}

serial {
    type = "InfantrySerialPort"
    devPath = "/dev/ttyACM0"
    baudRate = 921600
    update_head_atom = ["camera"]
    update_posture_atom = ["predictor"]
}

