global {
#     gForce = -9.8 # General
    gForce = -9.7949 # Nanjing(near to Changzhou)
#     gForce = -9.7833 # Guangzhou(near to Shenzhen)
    dragCoefficient = 0.0
    bullet42mm = false
}

camera {
    type = "DahengDriver"
    openMode = "Index"
    identifier = 1
    fps = 210.0
    fov = 30.0
    enableAutoWhiteBalance = true
    exposureTime = 0.005
    gain = 6

    dy = -0.04 # TODO
    dx = 0 # TODO
    image_frame_atom = ["armor_detector","recorder"]
    pitch = 1.0

}

armor_detector {
    type = "NNetArmorDetector"
    networkPath = "data/weights/armor_detect/opt-0625-001.onnx"  #network training file path
    inputWidth = 416
    inputHeight = 416
    numClasses = 8 #Number of classes
    numColors = 4  #Number of color
    bboxConfThresh = 0.6
    topK = 128
    nmsThresh = 0.01
    fftConfError = 0.15
    fftMinIou = 0.9
    maxArmorRatio = 4.0
    maxBarAngleDiff = 15.0
    armor_nnet_detect_available_atom = ["armor_locator"]
}

armor_locator {
    type = "ArmorLocator"
    largeArmor = [1, 4]
    detect_available_atom = ["strategy"]
}

strategy {
    type = "InfantryStrategy"
    set_target_atom = ["predict"]
}

predict{
    type = "ArmorPredictor"
    enablePredictor = false
    maxResidual = 1.0
    P = [0.05, 0.03, 0.1, 1.5, 1.5, 1.5]
    Q = [0.001, 0.001, 0.003, 0.001, 0.001, 0.003]
    R = [0.011206584, 0.0045113561, 0.0240242645488644]
    predict_success_atom = ["solver"]
}

solver {
    type = "AngleSolver"
    precision = 0.001
    delay = 0.20
    bulletSpeedDiscount = 1.0
    set_target_info_atom = ["serial"]
}

serial {
    type = "SerialPort"
    devPath = "/dev/ttyUSB0"
    baudRate = 921600
    # enableEnergyControl = true
    # energy_detector_control_atom = ["strategy","energy_detector"]
    update_head_atom = ["camera"]
    update_posture_atom = ["predict"]
}

recorder {
    type = "VideoRecorder"
    base = "record"
}
