global {
#     gForce = -9.8 # General
    gForce = -9.7949 # Nanjing(near to Changzhou)
#     gForce = -9.7833 # Guangzhou(near to Shenzhen)
    dragCoefficient = 0.0
    bullet42mm = false
}

# source {
#     type = "VideoReplay"
#     path = "/home/lzh/Downloads/video_test/RED_6/test2.mp4"
#     fps = 100
#     fov = 30.0
#     width = 640
#     height = 480
#     image_frame_atom = ["armor_detector"]
# }

camera {
    type = "DahengDriver"
    openMode = "Index"
    identifier = 1
    fps = 210.0
    fov = 30.0
    exposureTime = 0.005
    enableAutoWhiteBalance = true
    dy = 0.05 # TODO
    dz = -0.06 # TODO
    image_frame_atom = ["armor_detector","server","recorder"]
}

# armor_detector {
#     type = "ArmorDetector"
#     globalScale = 1.0
#     thresholdForBlue = [60,256,256]              # minBlue, maxGreen, maxRed
#     thresholdForRed = [40,256,256]               # minRed, maxBlue,maxGreen
#     bgrSubtractForBlue = 60                      # bgr subtract threshold for blue
#     bgrSubtractForRed = 60                       # bgr subtract threshold for red
#     minLightRectRatio = 0.15                     # width/height
#     maxLightRectRatio = 0.6                      # width/height
#     maxLightAngle = 60.0                         # angle(degree)
#     maxAreaRatio = 2.0                           # ellipseArea/contourAre#
#     minArmorRectRatio = 1.43                     # height/width
#     maxArmorRectRatio = 6.67                     # height/width
#     maxArmorAngle = 40.0                         # angle(degree)
#     maxLightBaseAngle = 15.0                     # abs(lightAngle-armorAngle)(degree)
#     maxParallelAngle = 10.0                      # abs(lightAngle1-lightAngle2)(degree)
#     minLightHeightRatio = 0.6                    # lightHeight/armorHeight
#     armor_detect_available_atom = ["armor_locator", "drawer"]
#     image_frame_atom = ["server"]
# }

armor_detector {
    type = "NNetArmorDetector"
    networkPath = "data/weights/armor_detect/opt-0625-001.onnx"  #network training file path
    inputWidth = 416
    inputHeight = 416
    numClasses = 8 #Number of classes
    numColors = 4  #Number of color
    bboxConfThresh = 0.6
    topK = 128
    nmsThresh = 0.3
    fftConfError = 0.15
    fftMinIou = 0.9
    armor_nnet_detect_available_atom = ["drawer", "armor_locator"]
    image_frame_atom = ["server"]
}

# energy_detector {
#     type = "EnergyDetector"
#     smallPredictMode = 0
#     bigPredictMode = 2
#     armorMinArea = 900.0
#     armorMaxArea = 2000.0
#     armorMinWHRatio = 1
#     armorMaxWHRatio = 3
#     armorMinAreaRatio = 0.8
#     stripMinArea = 7500.0
#     stripMaxArea = 10000.0
#     stripMinWHRatio = 1
#     stripMaxWHRatio = 5
#     stripMaxAreaRatio = 0.7
#     noiseArea = 2500.0
#     predictAngle = 0.402768288
#     radius = 148
#     offsetX = 0.0
#     offsetY = 0.0
#     preFrames = 20
#     energy_detect_available_atom = ["strategy"]
#     image_frame_atom = ["server"]
# }

armor_locator {
    type = "ArmorLocator"
    ratioThreshold = 8.5
    detect_available_atom = ["strategy"]
}

strategy {
    type = "InfantryStrategy"
    set_target_atom = ["predictor"]
    update_roi_atom = ["armor_detector"]
}

predictor{
    type = "ArmorPredictor"
    predict_success_atom = ["solver"]
}

solver {
    type = "AngleSolver"
    precision = 0.001
    delay = -0.2
    set_target_info_atom = ["serial"]
}

serial {
    type = "SerialPort"
    devPath = "/dev/ttyUSB0"
    baudRate = 921600
    # enableEnergyControl = true
    # energy_detector_control_atom = ["strategy","energy_detector"]
    update_head_atom = ["camera"]
    update_posture_atom = ["predictor"]
}

server {
    type = "HttpServer"
}

drawer {
    type = "ArmorDetectorDrawer"
    image_frame_atom = ["server"]
}

recorder {
    type = "VideoRecorder"
    base = "record"
}

server {
    type = "HttpServer"
}