global {
#     gForce = -9.8 # General
    gForce = -9.7949 # Nanjing(near to Changzhou)
#     gForce = -9.7833 # Guangzhou(near to Shenzhen)
    dragCoefficient = 0.0
    bullet42mm = false
}

server {
    type = "HttpServer"
    ethName = "eth0"
}

camera {
    type = "HikDriver"
    openMode = "Index"
    identifier = 1
    fps = 240.0
    fov = 30.0
    enableAutoWhiteBalance = true
    exposureTime = 0.005
    dx = 0.105
    dy = 0.04 # TODO
    dz = -0.050
    yaw = 0
    pitch = 0
    gain = 10
    image_frame_atom = ["armor_detector", "server", "predictor", "recorder"]
}

# source {
#     type = "VideoReplay"
#     path = "/home/artinx009/record/red.mp4"
#     fps = 60
#     fov = 30.0
#     width = 640
#     height = 480
#     image_frame_atom = ["armor_detector", "server"]
# }

armor_detector {
    type = "TensorRTDetector"
    debugView = false
    onnxPath = "data/weights/armor_detect/2024-07-19.onnx"
    numThresh = 0.7
    image_frame_atom = ["server"]
    armor_detect_available_atom = ["drawer", "armor_locator"]
}

drawer {
    type = "ArmorDetectorDrawer"
    image_frame_atom = ["server"]
}

armor_locator {
    type = "ArmorLocator"
    largeArmor = [1]
    detect_available_atom = ["strategy"]
}

strategy {
    type = "InfantryStrategy"
    set_target_atom = ["predictor"]
}


predictor {
  type = "CarPredictor"
  debugView = false
  enablePredictor = true
  enableFixYaw = true
  maxMatchDist = 0.3
  trackingThreshold = 5
  lostThreshold = 50
  maxMatchYaw = 0.7
  sigma2Qxyz = 20
  sigma2Qyaw = 20
  sigma2QR = 800
  Rxyz = 0.1
  Ryaw = 0.02
  car_predict_atom = ["solver"]
  car_predict_view_atom = ["drawer"]
}

solver {
    type = "AngleSolver"
    debugView = true
    delay = 0.1
    angle_solver_view_atom = ["drawer"]
    set_target_info_atom = ["serial"]
}

serial {
    type = "InfantrySerialPort"
    devPath = "/dev/ttyACM0"
    baudRate = 921600
    update_head_atom = ["camera"]
    update_posture_atom = ["predictor"]
}

recorder {
  type = "VideoRecorder"
  base = "record"
  segmentLength = 30.0
  fps = 60.0
}