global {
#     gForce = -9.8 # General
#    gForce = -9.7949 # Nanjing(near to Changzhou)
     gForce = -9.7833 # Guangzhou(near to Shenzhen)
    dragCoefficient = 0.0
    bullet42mm = false
}

camera {
    type = "DahengDriver"
    openMode = "Index"
    identifier = "1"
    cameraName = "test"
    enableAutoWhiteBalance = true
    fps = 120
    fov = 30.0
    flip = true
    gain = 10.0
    exposureTime = 0.0015
    dy = 0.03 # TODO
    dx = 0.0 # TODO
    pitch = -0.49 #degree
    image_frame_atom = ["armor_detector"]
}

armor_detector {
    type = "ArmorDetector"
    debugView = false
    binaryThresh = 40
    minLightRectRatio = 0.05   # width/height
    maxLightRectRatio = 0.6   # width/height
    maxLightAngle = 20.0       # angle(degree)
    min2lightLenRatio = 0.6   # light1.height / light2.height
    max2LightDiffAngle = 10.0
    minArmorRectRatio = 0.8   # width/height
    maxArmorRectRatio = 5.0   # width/height
    maxArmorAngle = 30       # angle(degree)
    minLargeArmorRatio = 3.2  # width / height
    numClassifyModelPath = "data/weights/armor_classify/mlp.onnx"
    numProbThresh = 0.7
    armor_detect_available_atom = ["drawer", "armor_locator"]
}

armor_locator {
    type = "ArmorLocator"
    ratioThreshold = 13
    detect_available_atom = ["strategy"]
}

strategy {
    type = "InfantryStrategy"
    set_target_atom = ["predict"]
}

predict {
    type = "CarPredictor"
    enablePredictor = true
    maxMatchYaw = 0.15
    maxMatchDist = 0.37
    trackingThreshold = 8
    lostThreshold = 20
    sigma2Qxyz = 20
    sigma2Qyaw = 100
    sigma2QR = 800
    Rxyz = 0.05
    Ryaw = 0.1
    car_predict_atom = ["solver"]
}

solver {
    type = "AngleSolver"
    precision = 0.001
    delay = 0.40
    bulletSpeedDiscount = 1.0
    set_target_info_atom = ["serial"]
}
serial {
    type = "InfantrySerialPort"
    devPath = "/dev/ttyUSB0"
    baudRate = 921600
    update_head_atom = ["camera"]
    update_posture_atom = ["predict"]
}
