global {
#     gForce = -9.8 # General
#    gForce = -9.7949 # Nanjing(near to Changzhou)
     gForce = -9.7833 # Guangzhou(near to Shenzhen)
    dragCoefficient = 0.0
    bullet42mm = false
}

camera {
    type = "HikDriver"
    openMode = "Index"
    identifier = "1"
    cameraName = "Camera"
    enableAutoWhiteBalance = true
    fps = 120
    fov = 30.0
    flip = true
    gain = 10.0
    exposureTime = 0.0015
    dy = 0.03 # TODO
    dx = 0.0 # TODO
    yaw = -0.5
    pitch = -1.0 #degree
    # image_frame_atom = ["armor_detector", "rune_detector", "recorder"]
    # image_frame_atom = ["armor_detector", "rune_detector", "server"]
    image_frame_atom = ["rune_detector", "server"]
}

armor_detector {
    type = "ArmorDetector"
    debugView = false
    binaryThresh = 60
    minLightRectRatio = 0.01   # width/height
    maxLightRectRatio = 0.6   # width/height
    maxLightAngle = 20.0       # angle(degree)
    min2lightLenRatio = 0.6   # light1.height / light2.height
    max2LightDiffAngle = 20.0
    minArmorRectRatio = 0.8   # width/height
    maxArmorRectRatio = 5.0   # width/height
    maxArmorAngle = 30       # angle(degree)
    minLargeArmorRatio = 3.2  # width / height
    numClassifyModelPath = "data/weights/armor_classify/mlp.onnx"
    numProbThresh = 0.7
    armor_detect_available_atom = ["armor_locator", "drawer"]
    image_frame_atom = ["server"]
}

rune_detector {
    type = "RuneDetector"
    debugView = false

    # bound for hsv
    lowerRed = [0, 0, 0]
    upperRed = [255, 255, 255]
    lowerBlue = [70, 0, 40]
    upperBlue = [180, 255, 255]

    binThresh = 60

    roiBinThresh = 100

    dilateKernel = 23
    minConvexHullThresh = 0.6  # for hull area ratio filter
    maxConvexHullThresh = 0.85
    minContourArea = 100         # for contour area filter

    rRoiSizeScale = 1.3
    minRRectAreaRatio = 1
    maxRRectSizeRatio = 1

    rPosScale = 8.0
    energy_detect_available_atom = ["energy_predictor"]
    image_frame_atom = ["server"]
}
armor_locator {
    type = "ArmorLocator"
    detect_available_atom = ["strategy"]
}

strategy {
    type = "InfantryStrategy"
    set_target_atom = ["predict"]
}

predict {
    type = "CarPredictor"
    enablePredictor = true
    maxMatchYaw = 1.0
    maxMatchDist = 0.20
    trackingThreshold = 8
    lostThreshold = 30
    sigma2Qxyz = 20
    sigma2Qyaw = 100
    sigma2QR = 800
    Rxyz = 0.05
    Ryaw = 0.1
    car_predict_atom = ["solver"]
}

energy_predictor{
    type = "EnergyPredictor"
    fanQueueLength = 20
    setMode = 2
    Qw = 0.08
    Qtheta = 0.08
    Qxyz = 0.08
    Qyaw = 0.08
    Rtheta = 0.4
    Rxyz = 0.05
    Ryaw = 0.4
    lostCnt = 20
    set_target_info_atom = ["serial"]
}

solver {
    type = "AngleSolver"
    delay = 0.04
    set_target_info_atom = ["serial"]
}

serial {
    type = "InfantrySerialPort"
    devPath = "/dev/ttyUSB0"
    baudRate = 921600
    update_head_atom = ["camera"]
    update_posture_atom = ["predict"]
}

recorder {
  type = "VideoRecorder"
  base = "record"
  segmentLength = 30.0
  fps = 60.0
}

server {
  type = "HttpServer"
}

drawer {
  type = "ArmorDetectorDrawer"
  image_frame_atom = ["server"]
}
