global {
  gForce = -9.8
  dragCoefficient = 0.0
  bullet42mm = false
}

# source {
#     type = "VideoReplay"
#     path = "/home/lambillda/rm/国赛/华师"
#     cameraName = "RadarCenter"
#     fps = 30.0
#     fov = 30.0
#     width = 1920
#     height = 1200
#     image_frame_atom = ["radar-detector","server"]
# }

camera {
    type = "DahengDriver"
    openMode = "Index"
    identifier = "1"
    #openMode = "SerialNumber"
    #identifier = "NE0200080112"
    cameraName="RadarCenter"
    fps = 20
    fov = 30.0
    gain= 22
    enableAutoWhiteBalance = true
    disableUndistort = true
    exposureTime = 0.025
    image_frame_atom = ["radar-detector","server","recorder"]
}

bot-locator{
    type = "BotLocator"
    selfRed=false
    mapPath="/home/lambillda/SDKs/map.png"
    rivalRHeightOffset=2
    rivalRoundHeightOffset=2
    selfRHeightOffset=1.5
    selfRoundHeightOffset=1.5
    image_frame_atom=["server"]
    sync_position_atom=["judge-system"]
}

radar-locator{
    type = "RadarLocator"
}

server{
    type = "HttpServer"
    enableRadar = true
    radar_locate_request_atom = ["radar-locator"]
}

radar-detector{
    type = "RadarNNetDetector"
    modelPath = "/home/lambillda/SDKs/new.engine"
    carConfidence=0.3
    armorConfidence=0.1
    greenThreshold=150
    selfRed=false
    image_frame_atom = ["server"]
    bot_locate_request_atom=["bot-locator"]
}

judge-system{
    type = "PosSynchronization"
    devPath="/dev/ttyACM0"
    baudRate=115200
}

recorder{
    type="VideoRecorder"
    base = "/home/lambillda/rm/国赛/深大"
    segmentLength = 15.0
    fps =20.0
}