global {
  gForce = -9.8
  dragCoefficient = 0.0
  bullet42mm = false
}

source {
    type = "VideoReplay"
 #  path = "/home/hzt/Videos/复活赛/上交/16_31_56.mkv"
   path = "/home/hzt/Videos/国赛/山科/17_29_42.mkv"
#    path = "/home/hzt/Videos/南部分区赛/5.27/center"
    cameraName = "RadarCenter"
    fps = 30.0
    fov = 30.0
    width = 1920
    height = 1200
    image_frame_atom = ["radar-detector","server"]
}

# camera {
#     type = "DahengDriver"
#     openMode = "Index"
#     identifier = "1"
#     #openMode = "SerialNumber"
#     #identifier = "NE0200080112"
#     cameraName="RadarCenter"
#     fps = 15
#     fov = 30.0
#     gain= 16
#     enableAutoWhiteBalance = true
#     disableUndistort = true
#     exposureTime = 0.025
#     image_frame_atom = ["radar-detector","server","recorder"]
# }

bot-locator{
    type = "BotLocator"
    selfRed=false
    mapPath="/home/hzt/workspace/model/map.png"
    rivalRHeightOffset=2
    rivalRoundHeightOffset=2
    selfRHeightOffset=1.5
    selfRoundHeightOffset=1.5
    image_frame_atom=["server"]
    sync_position_atom=["judge-system"]
}

radar-locator{
    type = "RadarLocator"
}

server{
    type = "HttpServer"
    enableRadar = true
    radar_locate_request_atom = ["radar-locator"]
}

radar-detector{
    type = "RadarNNetDetector"
    modelPath = "/home/hzt/workspace/model/new.engine"
    carConfidence=0.001
    armorConfidence=0.1
    greenThreshold=150
    selfRed=false
    image_frame_atom = ["server"]
    bot_locate_request_atom=["bot-locator"]
}

judge-system{
    type = "PosSynchronization"
    devPath="/dev/ttyACM0"
    baudRate=115200
}

recorder{
    type="VideoRecorder"
    base = "/home/hzt/Videos/国赛/山科"
    segmentLength = 15.0
    fps = 15.0
}