global {
  gForce = -9.8
  dragCoefficient = 0.0
  bullet42mm = false
}

camera1 {
    type = "DahengDriver"
    openMode = "SerialNumber"
    identifier = "KE0200080463"
    cameraName="center"
    fps = 200
    fov = 30.0
    enableAutoWhiteBalance = true
    disableUndistort = true
    exposureTime = 0.01
    gain=50
    image_frame_atom = ["server", "calibrator"]
}
recorder1{
    type="VideoRecorder"
    base = "record"
    segmentLength = 60.0
    fps = 60.0
}
camera2 {
    type = "DahengDriver"
    openMode = "SerialNumber"
    identifier = "NE0200080112"
    cameraName="left"
    fps = 200
    fov = 30.0
    gain=50
    enableAutoWhiteBalance = true
    disableUndistort = true
    exposureTime = 0.01
    image_frame_atom = ["server", "recorder2"]
}
recorder2{
    type="VideoRecorder"
    base = "record"
    segmentLength = 60.0
    fps = 60.0
}
position-tester{
    type="SerialPortTester"
    sync_position_atom=["judge-system"]
}
judge-system{
    type="PosSynchronization"
    devPath="/dev/ttyACM0"
    baudRate=115200
}
server {
  type = "HttpServer"
}
