global {
#     gForce = -9.8 # General
#    gForce = -9.7949 # Nanjing(near to Changzhou)
     gForce = -9.7833 # Guangzhou(near to Shenzhen)
    dragCoefficient = 0.0
    bullet42mm = false
}

source {
    type = "VideoReplay"
    path = "/home/artinx-008/workspace/codes/artinx-hub/record/17_15_41.mkv"
    fps = 10.0
    fov = 30.0
    width = 1440
    height = 1280
    image_frame_atom = ["rune_detector", "server"]
}

rune_detector {
    type = "RuneDetector"
    debugView = true

    modelPath = "data/weights/energy_detect/energy_416_noKpt.onnx"
    binThresh = 60

    roiBinThresh = 180

    dilateKernel = 23
    minConvexHullThresh = 0.6  # for hull area ratio filter
    maxConvexHullThresh = 0.85
    minContourArea = 100         # for contour area filter

    rRoiSizeScale = 1.2
    minRRectAreaRatio = 1
    maxRRectSizeRatio = 1

    rPosScale = 6.5
    energy_detect_available_atom = ["energy_predictor"]
    image_frame_atom = ["server"]
}

server {
  type = "HttpServer"
}

