global {
#     gForce = -9.8 # General
    gForce = -9.7949 # Nanjing(near to Changzhou)
#     gForce = -9.7833 # Guangzhou(near to Shenzhen)
    dragCoefficient = 0.0
    bullet42mm = false
    defaultBulletSpeed = 28.0
}

camera_front {
    type = "DahengDriver"
    openMode = "SerialNumber"
    identifier = "NE0200080111"
    cameraName = "camera_front"
    fps = 210.0
    fov = 30.0
    enableAutoWhiteBalance = true
    exposureTime = 0.005
    dy = 0.06 # TODO
    dz = -0.07
    image_frame_atom = ["armor_detector_front"]
}

camera_back {
    type = "DahengDriver"
    openMode = "SerialNumber"
    identifier = "KE0200080465"
    cameraName = "camera_back"
    fps = 210.0
    fov = 30.0
    enableAutoWhiteBalance = true
    exposureTime = 0.005
    isAtGun = false
    dy = 0.06 # TODO
    dx = -0.07
    yaw = 90.0
    pitch = 0.0 #TODO
    image_frame_atom = ["armor_detector_back"]
}


armor_detector_front {
    type = "ArmorDetector"
    debugView = false
    binaryThresh = 60
    minLightRectRatio = 0.1   # width/height
    maxLightRectRatio = 0.6   # width/height
    maxLightAngle = 20.0       # angle(degree)
    min2lightLenRatio = 0.6   # light1.height / light2.height
    max2LightDiffAngle = 10.0
    minArmorRectRatio = 0.8   # width/height
    maxArmorRectRatio = 5.0   # width/height
    maxArmorAngle = 30       # angle(degree)
    minLargeArmorRatio = 3.2  # width / height
    numClassifyModelPath = "data/weights/armor_classify/mlp.onnx"
    numProbThresh = 0.7
    armor_detect_available_atom = ["drawer_front", "armor_locator_front"]
    image_frame_atom = ["server"]
}

armor_detector_back {
    type = "ArmorDetector"
    debugView = false
    binaryThresh = 60
    minLightRectRatio = 0.1   # width/height
    maxLightRectRatio = 0.6   # width/height
    maxLightAngle = 20.0       # angle(degree)
    min2lightLenRatio = 0.6   # light1.height / light2.height
    max2LightDiffAngle = 10.0
    minArmorRectRatio = 0.8   # width/height
    maxArmorRectRatio = 5.0   # width/height
    maxArmorAngle = 30       # angle(degree)
    minLargeArmorRatio = 3.2  # width / height
    numClassifyModelPath = "data/weights/armor_classify/mlp.onnx"
    numProbThresh = 0.7
    armor_detect_available_atom = ["drawer_back", "armor_locator_back"]
    image_frame_atom = ["server"]
}

armor_locator_front {
    type = "ArmorLocator"
    group_id = 0
    detect_available_atom = ["strategy"]
}
armor_locator_back {
    type = "ArmorLocator"
    group_id = 1
    detect_available_atom = ["strategy"]
}

strategy {
    type = "SentryStrategy"
    ignoredId = [0, 2]
    maxDistance = 8.0
    set_target_atom = ["predictor"]
}

predictor {
    type = "CarPredictor"
    enablePredictor = true
    maxMatchDist = 0.32
    trackingThreshold = 5
    lostThreshold = 20
    sigma2Qxyz = 20
    sigma2Qyaw = 100
    sigma2QR = 800
    Rxyz = 0.05
    Ryaw = 0.1
    car_predict_atom = ["solver"]
}

solver {
    type = "AngleSolver"
    maxShootDeltaTheta = 30
    delay = 0.005
    set_target_info_atom = ["serial"]
}

server {
    type = "HttpServer"
}

serial {
    type = "SentrySerialPort"
    devPath = "/dev/ttyUSB0"
    baudRate = 921600
    update_head_atom = ["camera_front", "camera_back"]
    update_posture_atom = ["predictor"]
}

drawer_front {
    type = "ArmorDetectorDrawer"
    image_frame_atom = ["server"]
}
drawer_back {
    type = "ArmorDetectorDrawer"
    image_frame_atom = ["server"]
}

# recorder_front {
#    type = "VideoRecorder"
#     base = "record_front"
# }

# recorder_back {
#   type = "VideoRecorder"
#    base = "record_back"
# }
