global {
#     gForce = -9.8 # General
    gForce = -9.7949 # Nanjing(near to Changzhou)
#     gForce = -9.7833 # Guangzhou(near to Shenzhen)
    dragCoefficient = 0.0
    bullet42mm = false
    defaultBulletSpeed = 28.0
}

camera {
    type = "DahengDriver"
    openMode = "Index"
    identifier = 1
    fps = 210.0
    fov = 30.0
    enableAutoWhiteBalance = true
    exposureTime = 0.003
    dy = 0.06 # TODO
    dz = -0.07
    image_frame_atom = ["armor_detector","recorder"]
}

armor_detector {
    type = "ArmorDetector"
    debugView = false
    binaryThresh = 70
    minLightRectRatio = 0.1   # width/height
    maxLightRectRatio = 0.6   # width/height
    maxLightAngle = 20.0       # angle(degree)
    min2lightLenRatio = 0.6   # light1.height / light2.height
    max2LightDiffAngle = 10.0
    minArmorRectRatio = 0.8   # width/height
    maxArmorRectRatio = 5.0   # width/height
    maxArmorAngle = 30       # angle(degree)
    minLargeArmorRatio = 3.2  # width / height
    numClassifyModelPath = "data/weights/armor_classify/mlp.onnx"
    numProbThresh = 0.7
    armor_detect_available_atom = ["armor_locator"]
}

armor_locator {
    type = "ArmorLocator"
    largeArmor = [1]
    detect_available_atom = ["strategy"]
}

strategy {
    type = "SentryStrategy"
    ignoredId = [0, 2]
    maxDistance = 8.0
    set_target_atom = ["predictor"]
}

# predictor{
#     type = "ArmorPredictor"
#     enablePredictor = false
#     P = [0.05, 0.03, 0.1, 1.5, 1.5, 1.5]
#     Q = [0.001, 0.001, 0.003, 1.2, 1.2, 1.2]
#     R = [0.011206584, 0.0045113561, 0.0240242645488644]
#     predict_success_atom = ["solver"]
# }

predictor {
  type = "CarPredictor"
  enablePredictor = true
  maxMatchDist = 0.2
  maxMatchYaw = 0.2
  trackingThreshold = 5
  lostThreshold = 20
          #xc    yc       zc     yaw     vxc     vyc    vzc      vyaw     r
  Q = [0.0100, 0.0020, 0.0100, 0.0040, 0.0400, 0.0004 , 0.0400, 0.020, 0.0025]
          #xa    ya       za    yaw
  R = [0.0006, 0.0006, 0.0006, 0.0018]
  car_predict_atom = ["solver"]
}

solver {
    type = "AngleSolver"
    delay = 0.01
    set_target_info_atom = ["serial"]
}

serial {
    type = "SerialPort"
    devPath = "/dev/ttyUSB0"
    baudRate = 921600
    minBulletSpeed = 12.0
    maxBulletSpeed = 35.0
    update_head_atom = ["camera"]
    update_posture_atom = ["predictor"]
}

recorder {
    type = "VideoRecorder"
    base = "record"
}
