global {
#     gForce = -9.8 # General
    gForce = -9.7949 # Nanjing(near to Changzhou)
#     gForce = -9.7833 # Guangzhou(near to Shenzhen)
    dragCoefficient = 0.0
    bullet42mm = false
}

server {
    type = "HttpServer"
}

camera_up {
    type = "DahengDriver"
    openMode = "Index"
    identifier = 1 # TODO: use SN RS0222008020
    fps = 20.0
    fov = 48.0
    exposureTime = 0.01
    dy = 0.05 # TODO
    dz = -0.06 # TODO
    image_frame_atom = ["detector_up","server"]
}
camera_down {
    type = "DahengDriver"
    openMode = "Index"
    identifier = 2 # TODO: use SN RS0225008020
    fps = 20.0
    fov = 23.0
    exposureTime = 0.01
    dy = 0.05 # TODO
    dz = -0.06 # TODO
    image_frame_atom = ["detector_down","server"]
}

detector_up {
    type = "FakeCarDetector"
    car_detect_available_atom = ["armor_detector_up"]
}
detector_down {
    type = "FakeCarDetector"
    car_detect_available_atom = ["armor_detector_down"]
}

armor_detector_up {
    type = "ArmorDetector"
    globalScale = 1.0
    thresholdForBlue = [120,256,256]
    thresholdForRed = [40,256,256]
    maxAreaRatio = 2.0
    maxLightAngle = 0.3
    maxLightRectRatio = 10.0
    maxArmorRectRatio = 0.5
    maxArmorAngle = 0.8
    minLightBaseAngle = 0.3
    maxParallelAngle = 0.7
    minLightHeightRatio = 0.6
    armor_detect_available_atom = ["armor_locator_up", "drawer_up"]
    image_frame_atom = ["server"]
}
armor_detector_down {
    type = "ArmorDetector"
    globalScale = 1.0
    thresholdForBlue = [120,256,256]
    thresholdForRed = [40,256,256]
    maxAreaRatio = 2.0
    maxLightAngle = 0.3
    maxLightRectRatio = 10.0
    maxArmorRectRatio = 0.5
    maxArmorAngle = 0.8
    minLightBaseAngle = 0.3
    maxParallelAngle = 0.7
    minLightHeightRatio = 0.6
    armor_detect_available_atom = ["armor_locator_down", "drawer_down"]
    image_frame_atom = ["server"]
}

drawer_up {
    type = "ArmorDetectorDrawer"
    image_frame_atom = ["server"]
}
drawer_down {
    type = "ArmorDetectorDrawer"
    image_frame_atom = ["server"]
}

armor_locator_up {
    type = "ArmorLocator"
    group_id = 0
    detect_available_atom = ["strategy"]
}
armor_locator_down {
    type = "ArmorLocator"
    group_id = 1
    detect_available_atom = ["strategy"]
}

strategy {
    type = "SentryStrategy"
    distanceThreshold = 0.0
    detectedTTL = 1.0
    set_target_atom = ["solver_up","solver_down"]
}

solver_up {
    type = "AngleSolver"
    group_id = 0
    precision = 0.001
    delay = -0.2
    set_target_info_atom = ["serial"]
}
solver_down {
    type = "AngleSolver"
    group_id = 1
    precision = 0.001
    delay = -0.2
    set_target_info_atom = ["serial"]
}

serial {
    type = "SerialPort"
    devPath = "/dev/ttyUSB0"
    baudRate = 921600
    headHeightOffset1 = 0.2 # TODO
    headHeightOffset2 = -0.2 # TODO
    update_head_atom = ["solver_up","solver_down","strategy"]
    update_posture_atom = ["solver_up","solver_down"]
}
