global {
    gForce = -9.7949 # Nanjing(near to Changzhou)
    dragCoefficient = 0.0
    bullet42mm = false
}

camera {
  type = "DahengDriver"
  openMode = "Index"
  cameraName="first"
  identifier = 1
  fps = 210.0  fov = 30.0
  exposureTime = 0.008
  enableAutoWhiteBalance = true
  gain= 100
  image_frame_atom = ["server","recorder"]
}
camera2 {
  type = "DahengDriver"
  openMode = "Index"
  identifier = 2
  cameraName="second"
  fps = 210.0
  fov = 30.0
  exposureTime = 0.008
  enableAutoWhiteBalance = true
  gain= 100
  image_frame_atom = ["server","recorder1"]
}
server {
  type = "HttpServer"
}
recorder {
  type = "VideoRecorder"
  base = "record"
  segmentLength = 60.0
  fps = 60.0
}
recorder2 {
  type = "VideoRecorder"
  base = "record"
  segmentLength = 60.0
  fps = 60.0
}
tester{
type = "SerialPortTester"
sync_position_atom=["judge-system"]
}
judge-system{
type="PosSynchronization"
devPath="/dev/ttyUSB0"
baudRate=115200
}


