global {
  gForce = -9.8
  dragCoefficient = 0.0
  bullet42mm = false
}
armor_detector_test {
  type = "ArmorDetectorTester"
  path = <image path>
  extension = ".png"
  image_frame_atom = ["server"]
  car_detect_available_atom = ["armor_detector"]
}
armor_detector {
  type = "ArmorDetector"
  #ycm: 为他人加入detector的setting提供参考。因此这个也commit了。
  #color settings
  enemyColor = 0   #index of following settings
  colorName = ["red", "blue"]
  colorRangeLeft = [15,90]
  colorRangeRight = [150,124]
  colorRangeComplement = [true, false]
  #light\armor suitable settings
  colorThreshold = 80  # 100-20
  brightThreshold = 60 # minArea = 50; # (lzj) modified params
  minArea = 70	# light area
  maxArea = 1000	# light area
  maxAngle = 45
  maxAngleDiff = 30
  maxLengthDiffRatio = 0.5
  maxDeviationAngle = 50
  maxYDiffRatio = 0.5 # maxXDiffRatio = 4.5
  maxXDiffRatio = 4.0 # (lzj) new params
  minXDiffRatio = 0.9
  armor_detect_available_atom = ["armor_detector_test"]
  armor_detect_available_atom = ["armor_detector_test"]
}
server {
  type = "HttpServer"
}
