global {
  gForce = -9.8
  dragCoefficient = 0.0
  bullet42mm = false
}
replay {
  type = "ImageSequenceReplay"
  path = <image path>
  extension = ".png"
  fps = 30.0
  fov = <fov>
  width = 640
  height = 480
  image_frame_atom = ["server","fake_car_detector"]
}
fake_car_detector {
  type = "FakeCarDetector"
  car_detect_available_atom = ["armor_detector"]
}
armor_detector {
  type = "ArmorDetector"
  runningTypeString = "DATASET_BASED_TEST" # one of {"RELEASE", "DEBUG", "DATASET_BASED_TEST"}. The running mode for detector.
  #color settings
  enemyColor = 0   #index of following settings
  colorName = ["red", "blue"] #you can add new colors and their ranges based on the light effect of the environment.
  colorHueRangeLowerBound = [15,90]
  colorHueRangeUpperBound = [150,124]
  colorHueRangeIsComplemented = [true, false]
  #light\armor criteria settings
  minArea = 70	# light area
  maxArea = 1000	# light area
  maxAngle = 45
  maxAngleDiff = 30
  maxLengthDiffRatio = 0.5
  maxDeviationAngle = 50
  maxYDiffRatio = 0.5 # maxXDiffRatio = 4.5
  maxXDiffRatio = 4.0
  minXDiffRatio = 0.9
  armor_detect_available_atom = ["armor_detector_drawer"]
}
armor_detector_drawer {
  type = "ArmorDetectorDrawer",
  image_frame_atom = ["server"]
}
server {
  type = "HttpServer"
}
