global {
  gForce = -9.8
  dragCoefficient = 0.0
  bullet42mm = false
}
camera{
type="DahengDriver"
openMode="Index"
   identifier = 1
    fps = 210.0
    fov = 30.0
    exposureTime = 0.005
    enableAutoWhiteBalance = true
    gain=20.0
    dy = 0.05 # TODO
    dz = -0.06 # TODO
    image_frame_atom = ["server"]
}
# video_replay {
#   type = "VideoReplay"
#   path = <video path>
#   fps = 30.0
#   fov = <fov>
#   width = 640
#   height = 480
#   image_frame_atom = ["car_detector"]
# }
# car_detector {
#   type = "CarDetector"
#   inputWidth = 640
#   inputHeight = 640
#   xmlPath = "/home/lambillda/codes/artinx-hub/data/weights/car300/car300.xml"
#   binPath = "/home/lambillda/codes/artinx-hub/data/weights/car300/car300.bin"
#   nmsThreshold = 0.6
#   boundingBoxThreshold = 0.7
#   deviceName = "CPU"
#   car_detect_available_atom = ["car_detector_drawer"]
#   numClasses = 5
#   carId = 0
# }
# car_detector_drawer {
#   type = "CarDetectorDrawer"
#   image_frame_atom = ["server"]
# }
server {
  type = "HttpServer"
}
