global {
  gForce = -9.8
  dragCoefficient = 0.0
  bullet42mm = false
}
video_replay {
	type = "VideoReplay"
	path = <video path>
	fps = 30.0
	image_frame_atom = ["car_detector"]
}
car_detector {
	type = "CarDetector"
	inputWidth = 640
	inputHeight = 640
	xmlPath = "data/weights/car300/car300.xml"
	binPath = "data/weights/car300/car300.bin"
  nmsThreshold = 0.6
  boundingBoxThreshold = 0.7
  deviceName = "CPU"
	car_detect_available_atom = ["car_detector_drawer"]
}
car_detector_drawer {
	type = "CarDetectorDrawer"
	image_frame_atom = ["server"]
}
server {
	type = "HttpServer"
}
