global {
  gForce = -9.8
  dragCoefficient = 0.0
  bullet42mm = false
}
source {
    type = "VideoReplay"
    path = "/home/artinx/Downloads/buff.mp4"
    cameraName = "VideoReplay"
    fps = 60.0
    fov = 30.0
    width = 960
    height = 600
    image_frame_atom = ["server", "energy_detector"]
}

energy_detector{
    type = "NNetEnergyDetector"
    debugView = true
    modelPath = "data/weights/energy_detect/energy_R5Kpt_416.onnx"
    nmsThreshold = 0.6
    confThreshold = 0.4
    imgSize = 416
    kptNum = 5
    classNum = 6
    anchorNum = 1
    image_frame_atom = ["server"]
}

server{
    type = "HttpServer"
}
