global {
  gForce = -9.8
  dragCoefficient = 0.0
  bullet42mm = false
}

camera {
    type = "HikDriver"
    openMode = "Index"
    identifier = "1"
    cameraName = "test"
    enableAutoWhiteBalance = false
    fps = 34.0
    fov = 30.0
    gain = 16.0
    exposureTime = 0.01
    dy = 0.05 # TODO
    dz = -0.06 # TODO
    image_frame_atom = ["server"]
}

server{
    type = "HttpServer"
}
