global {
  gForce = -9.8
  dragCoefficient = 0.0
  bullet42mm = false
}

camera {
    type = "HikDriver"
    openMode = "Index"
    identifier = 1
    fps = 210.0
    fov = 30.0
    enableAutoWhiteBalance = true
    exposureTime = 0.005
    dx = 0.105
    dy = 0.04 # TODO
    dz = -0.050
    yaw = 0
    pitch = 0
    gain = 10
    image_frame_atom = ["server"]
}

server{
    type = "HttpServer"
}
