global {
#     gForce = -9.8 # General
    gForce = -9.7949 # Nanjing(near to Changzhou)
#     gForce = -9.7833 # Guangzhou(near to Shenzhen)
    dragCoefficient = 0.0
    bullet42mm = false
}

camera {
    type = "DahengDriver"
    openMode = "Index"
    identifier = 1
    fps = 210.0
    fov = 30.0
    enableAutoWhiteBalance = true
    exposureTime = 0.002
    dx = -0.0596
    dy = -0.003 # TODO
    dz = -0.169
    yaw = 0
    pitch = -3.4
    gain = 12
    image_frame_atom = ["armor_detector","server","predictor"]
}

armor_detector {
    type = "TensorRTDetector"
    debugView = false
    onnxPath = "data/weights/armor_detect/best_trt.onnx"
    numThresh = 0.7

    image_frame_atom = ["server"]
    armor_detect_available_atom = ["drawer", "labeler"]
}

server {
  type = "HttpServer"
  ethName = "l4tbr0"
}

drawer {
    type = "ArmorDetectorDrawer"
    image_frame_atom = ["server"]
}

labeler {
    type = "ArmorLabeler"
    savePath = "data/labels/"
}