#atom name{} + .... + atom name{}

ore_exchange_rectifier {
  type = "OreExchangeRectifier"
  image_frame_atom = ["CameraFrame"]
  prototxt = "data/weights/SuperResolution/sr.prototxt"
  caffemodel = "data/weights/SuperResolution/sr.caffemodel"
  validDetectionRequired = 10
  permissibleAngleRangeOfError = 0.1
  deltaTime = 0.01
  ore_detect_available_atom = ["SerialPort"];
}
server {
  type = "HttpServer"
}