global {
#     gForce = -9.8 # General
    gForce = -9.7949 # Nanjing(near to Changzhou)
#     gForce = -9.7833 # Guangzhou(near to Shenzhen)
    dragCoefficient = 0.0
    bullet42mm = false
    isRed = true #red:true     blue:false
}

# source {
#     type = "VideoReplay"
#     path = "/opt/artinx-hub/record/17:41:11.mkv"
#     fps = 60
#     fov = 30.0
#     width = 1920
#     height = 1200
#     image_frame_atom = ["armor_detector"]
# }

camera {
    type = "DahengDriver"
    openMode = "Index"
    identifier = 1
    fps = 210.0
    fov = 30.0
    exposureTime = 0.0005
#     exposureTime = 0.01
    enableAutoWhiteBalance = true
    # image_frame_atom = ["armor_detector","server","recorder"]
    image_frame_atom = ["armor_detector","server"]
}

armor_detector {
    type = "ArmorDetector"
    debugView = false
    binaryThresh = 100
    minLightRectRatio = 0.1   # width/height
    maxLightRectRatio = 0.6   # width/height
    maxLightAngle = 5.0       # angle(degree)
    min2lightLenRatio = 0.6   # light1.height / light2.height
    max2LightDiffAngle = 5.0
    minArmorRectRatio = 0.8   # width/height
    maxArmorRectRatio = 5.0   # width/height
    maxArmorAngle = 13       # angle(degree)
    minLargeArmorRatio = 3.2  # width / height
    numClassifyModelPath = "data/weights/armor_classify/cls_num.onnx"
    numProbThresh = 0.7
    armor_detect_available_atom = ["drawer", "armor_locator"]
    image_frame_atom = ["server"]
}

# armor_detector {
#     type = "NNetArmorDetector"
#     networkPath = "data/weights/armor_detect/opt-0625-001.onnx"  #network training file path
#     inputWidth = 416
#     inputHeight = 416
#     numClasses = 8 #Number of classes
#     numColors = 4  #Number of color
#     bboxConfThresh = 0.65
#     topK = 128
#     nmsThresh = 0.3
#     fftConfError = 0.15
#     fftMinIou = 0.9
#     maxArmorRatio = 4.0
#     maxBarAngleDiff = 15.0
#     armor_nnet_detect_available_atom = ["drawer", "armor_locator"]
#     image_frame_atom = ["server"]
# }

armor_locator {
    type = "ArmorLocator"
    ratioThreshold = 3.0
    largeArmor = [1]
}

server {
    type = "HttpServer"
}

drawer {
    type = "ArmorDetectorDrawer"
    image_frame_atom = ["server"]
}

# recorder {
#     type = "VideoRecorder"
#     base = "record"
# }