global {
  gForce = -9.8
  dragCoefficient = 0.0
  bullet42mm = false
}

syncer{
    type="PosSynchronization"
#     type="SerialPort"
    devPath="/dev/ttyUSB0"
    baudRate=115200
}

data_generator{
    type="SerialPortTester"
    sync_position_atom = ["syncer"]
}

# server{
#     type = "HttpServer"
#     enableRadar = true
#     radar_locate_request_atom = ["radar"]
# }
