global {
  gForce = -9.8
  dragCoefficient = 0.0
  bullet42mm = false
}

camera {
    type = "DahengDriver"
    openMode = "Index"
    cameraName="RadarCenter"
    identifier = 1
    fps = 30.0
    fov = 30.0
    exposureTime = 0.008
    gain=14
    enableAutoWhiteBalance=true
    enableAutoWhiteBalance = true
    dy = 0.05 # TODO
    dz = -0.06 # TODO
    image_frame_atom = ["radar-detector","server"]
}

# source {
#     type = "VideoReplay"
#     # path = "/home/hzt/Videos/6.26/桂理工/center"
#     path = "/home/hzt/Videos/6.25/CENTER"
#     cameraName = "RadarCenter"
#     fps = 30.0
#     fov = 30.0
#     width = 1920
#     height = 1200
#     image_frame_atom = ["radar-detector","server"]
# }

radar-detector{
    type = "RadarNNetDetector"
    modelPath = "/home/hzt/workspace/model/new.engine"
    carConfidence=0.7
    armorConfidence=0.0
    greenThreshold=150
    selfRed=false
    image_frame_atom = ["server"]
    bot_locate_request_atom=["bot-locator"]
}

bot-locator{
    type = "BotLocator"
    selfRed=false
    mapPath="/home/hzt/workspace/model/map.png"
    rivalRHeightOffset=2
    rivalRoundHeightOffset=2
    selfRHeightOffset=1.5
    selfRoundHeightOffset=1.5
    image_frame_atom=["server"]
    sync_position_atom=["judge-system"]
}

radar-locator{
    type = "RadarLocator"
}

server{
    type = "HttpServer"
    enableRadar = true
    radar_locate_request_atom = ["radar-locator"]
}

judge-system{
    type = "PosSynchronization"
    devPath="/dev/ttyACM0"
    baudRate=115200
}

#recorder{
    #type = "VideoRecorder"
    #base = "/home/thirtyni/Videos/6.23/center"
    #segmentLength = 30
    #fps = 30
#}

