global {
  gForce = -9.8
  dragCoefficient = 0.0
  bullet42mm = false
}

# camera {
#     type = "DahengDriver"
#     openMode = "Index"
#     identifier = 1
#     fps = 210.0
#     fov = 30.0
#     exposureTime = 0.005
#     enableAutoWhiteBalance = true
#     dy = 0.05 # TODO
#     dz = -0.06 # TODO
#     image_frame_atom = ["armor_detector","server","recorder"]
# }
source {
    type = "VideoReplay"
    path = "/home/lambillda/Videos/test.mp4"
    cameraName = "RadarCenter"
    fps = 60.0
    fov = 30.0
    width = 1920
    height = 1200
    image_frame_atom = ["radar-detector","server"]
}

radar-detector{
    type = "RadarNNetDetector"
    modelPath = "/home/lambillda/Codes/artinx-hub/data/weights/radar_detect/yolov7e6.engine"
    image_frame_atom = ["server"]
}

server{
    type = "HttpServer"
    enableRadar = true
    radar_locate_request_atom = ["radar"]
}
