global {
  gForce = -9.8
  dragCoefficient = 0.0
  bullet42mm = false
}

# camera {
#     type = "DahengDriver"
#     openMode = "Index"
#     identifier = 1
#     fps = 210.0
#     fov = 30.0
#     exposureTime = 0.005
#     enableAutoWhiteBalance = true
#     dy = 0.05 # TODO
#     dz = -0.06 # TODO
#     image_frame_atom = ["armor_detector","server","recorder"]
# }

source {
    type = "VideoReplay"
    path = "/home/lambillda/Videos/radar_record/5.25/CENTER"
    cameraName = "RadarCenter"
    fps = 60.0
    fov = 30.0
    width = 1920
    height = 1200
    image_frame_atom = ["radar-detector","server"]
}

radar-detector{
    type = "RadarNNetDetector"
    modelPath = "/home/lambillda/SDKs/save.engine"
    mapPath="/home/lambillda/SDKs/map.png"
    minConfidence=0.5
    image_frame_atom = ["server"]
    bots_locate_request_atom=["bot-locator"]
}

radar-locator{
    type = "RadarLocator"
    
}

bot-locator{
    type = "BotsLocator"
    mapPath="/home/lambillda/SDKs/map.png"
    image_frame_atom=["server"]
}

server{
    type = "HttpServer"
    enableRadar = true
    radar_locate_request_atom = ["radar-locator"]
}

#recorder{
    #type = "VideoRecorder"
    #base = "/home/thirtyni/Videos/6.23/center"
    #segmentLength = 30
    #fps = 30
#}
