global {
  gForce = -9.8
  dragCoefficient = 0.0
  bullet42mm = false
}
source {
    type = "VideoReplay"
    path = "/home/lambillda/Videos/ARTINX/test1.mp4"
    fps = 20.0
    fov = 30.0
    width = 640
    height = 480
    image_frame_atom = ["server"]
}
server{
    type = "HttpServer"
    enableRadar = true
}
