global {
  gForce = -9.8
  dragCoefficient = 0.0
  bullet42mm = false
}

source {
    type = "VideoReplay"
    path = "/home/hzt/Videos/6.25/CENTER/16:0:56.mkv"
    cameraName = "RadarCenter"
    fps = 30.0
    fov = 30.0
    width = 1920
    height = 1280
    image_frame_atom = ["radar_detector","server"]
}

radar_detector{
    type = "RadarNNetDetector"
    modelPath = "/home/hzt/workspace/model/yv7.engine"
    minConfidence=0.55
    image_frame_atom = ["server"]
}

radar_locator{
    type="RadarLocator"
    radar_locate_succeed_atom=["server"]
}

server{
    type = "HttpServer"
    enableRadar = true
    radar_locate_request_atom = ["radar_locator"]
}
