global {
    gForce = -9.7833 # Guangzhou(near to Shenzhen)
    dragCoefficient = 0.0
    bullet42mm = false
    isRed = false
}

rosCamera {
    type = "RosCamera"
    imageTopic = "/image"
    cameraInfoTopic = "/camera_info"
    image_frame_atom = ["server", "armor_detector"]
}

armor_detector {
    type = "TensorRTDetector"
    debugView = false
    onnxPath = "data/weights/armor_detect/best_trt.onnx"
    numThresh = 0.8
    # armor_detect_available_atom = ["drawer"]
    # armor_detect_available_atom = ["drawer"]

    image_frame_atom = ["server"]
    armor_detect_available_atom = ["drawer", "armor_locator"]
}

armor_locator {
    type = "ArmorLocator"
    largeArmor = [1]
    detect_available_atom = ["strategy"]
}

strategy {
    type = "InfantryStrategy"
    set_target_atom = ["predictor"]
}

predictor {
  type = "CarPredictor"
  enablePredictor = true
  maxMatchDist = 0.32
  trackingThreshold = 5
  lostThreshold = 50
  maxMatchYaw = 0.7
  sigma2Qxyz = 20
  sigma2Qyaw = 100
  sigma2QR = 800
  Rxyz = 0.1
  Ryaw = 0.02
  car_predict_atom = ["solver"]
}

drawer {
    type = "ArmorDetectorDrawer"
    image_frame_atom = ["server"]
}

server {
  type = "HttpServer"
}