global {
    gForce = -9.7833 # Guangzhou(near to Shenzhen)
    dragCoefficient = 0.0
    bullet42mm = false
    isRed = false
}

rosCamera {
    type = "RosCamera"
    imageTopic = "/image"
    cameraInfoTopic = "/camera_info"
    image_frame_atom = ["server", "armor_detector"]
}

armor_detector {
    type = "TensorRTDetector"
    debugView = false
    onnxPath = "data/weights/armor_detect/best_trt.onnx"
    numThresh = 0.7
    # armor_detect_available_atom = ["drawer"]
    # armor_detect_available_atom = ["drawer"]

    image_frame_atom = ["server"]
    armor_detect_available_atom = ["drawer"]
}

drawer {
    type = "ArmorDetectorDrawer"
    image_frame_atom = ["server"]
}

server {
  type = "HttpServer"
}