global {
    gForce = -9.7833 # Guangzhou(near to Shenzhen)
    dragCoefficient = 0.0
    bullet42mm = false
    isRed = false
}

rosCamera {
    type = "RosCamera"
    imageTopic = "/image"
    cameraInfoTopic = "/camera_info"
    jointTopic = "/joint"
    image_frame_atom = ["server", "armor_detector", "predictor"]
}

armor_detector {
    type = "TensorRTDetector"
    debugView = false
    onnxPath = "data/weights/armor_detect/best_trt.onnx"
    numThresh = 0.8
    # armor_detect_available_atom = ["drawer"]
    # armor_detect_available_atom = ["drawer"]

    image_frame_atom = ["server"]
    armor_detect_available_atom = ["drawer", "armor_locator"]
}

# armor_detector {
#     type = "ArmorDetector"
#     debugView = false
#     binaryThresh = 60
#     minLightRectRatio = 0.1   # width/height
#     maxLightRectRatio = 0.6   # width/height
#     maxLightAngle = 30.0       # angle(degree)
#     min2lightLenRatio = 0.6   # light1.height / light2.height
#     max2LightDiffAngle = 10.0
#     minArmorRectRatio = 0.8   # width/height
#     maxArmorRectRatio = 11.0   # width/height
#     maxArmorAngle = 20       # angle(degree)
#     minLargeArmorRatio = 3.2  # width / height
#     numClassifyModelPath = "data/weights/armor_classify/mlp.onnx"
#     numProbThresh = 0.7
#     armor_detect_available_atom = ["drawer", "armor_locator"]
#     # armor_detect_available_atom = ["drawer"]

#     image_frame_atom = ["server"]
# }

armor_locator {
    type = "ArmorLocator"
    largeArmor = [1]
    detect_available_atom = ["strategy"]
}

strategy {
    type = "InfantryStrategy"
    set_target_atom = ["predictor"]
}

predictor {
  type = "CarPredictor"
  debugView = true
  enablePredictor = true
  enableFixYaw = true
  fixYawThresh = 30
  maxMatchDist = 0.2
  trackingThreshold = 5
  lostThreshold = 50
  maxMatchYaw = 0.7
  sigma2Qxyz = 20
  sigma2Qyaw = 100
  sigma2QR = 800
  Rxyz = 0.1
  Ryaw = 0.02
  car_predict_atom = ["solver"]
  car_predict_view_atom = ["drawer"]
}

solver {
    type = "AngleSolver"
    debugView = true
    delay = 0.04
    angle_solver_view_atom = ["drawer"]
}

drawer {
    type = "ArmorDetectorDrawer"
    image_frame_atom = ["server"]
}

server {
  type = "HttpServer"
}