global {
#     gForce = -9.8 # General
    gForce = -9.7949 # Nanjing(near to Changzhou)
#     gForce = -9.7833 # Guangzhou(near to Shenzhen)
    dragCoefficient = 0.0
    bullet42mm = false
    defaultBulletSpeed = 15.0
}

camera {
    type = "HikDriver"
    openMode = "Index"
    identifier = 1
    fps = 210.0
    fov = 30.0
    exposureTime = 0.003
    enableAutoWhiteBalance = true
    dy = 0.05 # TODO
    dz = -0.06 # TODO
    flip = true
    image_frame_atom = ["server", "rune_detector"]
}

# source {
#    type = "VideoReplay"
# #    path = "/home/artinx-008/Videos/blue_2.mp4"
#    path = "/home/artinx-008/Videos/buff_blue.mp4"
#    fps = 30
#    fov = 30.0
#    width = 1280
#    height = 1080
#    image_frame_atom = ["rune_detector", "server"]
# }

rune_detector {
    type = "RuneDetector"
    debugView = true

    # bound for hsv
    lowerRed = [0, 0, 0]
    upperRed = [180, 255, 255]
    lowerBlue = [70, 0, 40]
    upperBlue = [180, 255, 255]
    binThresh = 10

    roiBinThresh = 150

    dilateKernel = 13
    minConvexHullThresh = 0.6  # for hull area ratio filter
    maxConvexHullThresh = 0.85
    minContourArea = 100         # for contour area filter

    rRoiSizeScale = 1.0

    rPosScale = 8.3
    energy_detect_available_atom = ["energy_predictor"]
    image_frame_atom = ["server"]
}

energy_predictor{
    type = "EnergyPredictor"
    fanQueueLength = 20
    Qw = 0.08
    Qtheta = 0.08
    Qxyz = 0.08
    Qyaw = 0.08
    Rtheta = 0.4
    Rxyz = 0.05
    Ryaw = 0.4
    lostCnt = 20
    set_target_info_atom = ["serial"]
    # set_target_info_atom = []
}

server {
    type = "HttpServer"
}
serial {
    type = "InfantrySerialPort"
    devPath = "/dev/ttyUSB0"
    baudRate = 921600
    update_head_atom = ["camera"]
}
