global {
  # gForce = -9.8 # General
    gForce = -9.7949 # Nanjing(near to Changzhou)
  # gForce = -9.7833 # Guangzhou(near to Shenzhen)
    dragCoefficient = 0.0
    bullet42mm = false
}

# source {
#     type = "VideoReplay"
#     path = "/home/artinx002/Downloads/new_buff.mp4"
#     fps = 20.0
#     fov = 30.0
#     width = 640
#     height = 640
#     image_frame_atom = ["energy_detector", "server"]
# }

source {
    type = "VideoReplay"
    path = "/home/artinx-008/Desktop/workspace/codes/test_video/buff_red.mp4"
    fps = 20.0
    fov = 30.0
    width = 640
    height = 320
    image_frame_atom = ["energy_detector", "server"]
}

# camera {
#     type = "DahengDriver"
#     openMode = "Index"
#     identifier = 1
#     fps = 210.0
#     fov = 30.0
#     exposureTime = 0.001
#     dy = 0.05 # TODO
#     dz = -0.06 # TODO
#     image_frame_atom = ["energy_detector","server"]
# }

energy_detector {
    type = "EnergyDetector"
    binaryThreshold = 20
    colorDiffThreshold = 80
    minContourArea = 50
    maxContourArea = 300
    minLightAreaRatio = 0.05
    maxLightAreaRatio = 0.7
    directionCoefficient = 2.3
    vaneLength = 1.2
    roiSize = 2.5
    maxRLabelRectRatio = 1.6
    energy_detect_available_atom = ["drawer"]
    image_frame_atom = ["server"]
}

drawer {
    type = "ArmorDetectorDrawer"
    image_frame_atom = ["server"]
}

server {
    type = "HttpServer"
}
