global {
    gForce = -9.7949 # Nanjing(near to Changzhou)
    dragCoefficient = 0.0
    isRed = false
    bullet42mm = false
}

# source {
#    type = "VideoReplay"
#    path = <path>
#    fps = 30
#    fov = 30.0
#    width = 640
#    height = 480
#    image_frame_atom = ["armor_detector", "server"]
# }

# source {
#     type = "ImageSequenceReplay"
#     path = <>
#     extension = "png"
#     fps = 1
#     fov = 30.0
#     width = 640
#     height = 360
#     binaryThresh = 240
#     image_frame_atom = ["armor_detector", "server"]
# }

camera {
    type = "DahengDriver"
    openMode = "Index"
    identifier = 1
    fps = 210.0
    fov = 30.0
    exposureTime = 0.005
    dy = 0.05 # TODO
    dz = -0.06 # TODO
    image_frame_atom = ["armor_detector","server"]
}

# source {
#    type = "VideoReplay"
#    path = <>
#    cameraName = "video"
#    fps = 100
#    fov = 30.0
#    width = 640
#    height = 480
#    image_frame_atom = ["armor_detector"]
# }

armor_detector {
    type = "ArmorDetector"
    debugView = false
    binaryThresh = 100
    minLightRectRatio = 0.1   # width/height
    maxLightRectRatio = 0.6   # width/height
    maxLightAngle = 5.0       # angle(degree)
    min2lightLenRatio = 0.6   # light1.height / light2.height
    max2LightDiffAngle = 5.0
    minArmorRectRatio = 0.8   # width/height
    maxArmorRectRatio = 5.0   # width/height
    maxArmorAngle = 13       # angle(degree)
    minLargeArmorRatio = 3.2  # width / height
    numClassifyModelPath = "data/weights/armor_classify/cls_num.onnx"
    numProbThresh = 0.7
    armor_detect_available_atom = ["drawer", "armor_locator"]
    image_frame_atom = ["server"]
}

drawer {
    type = "ArmorDetectorDrawer"
    image_frame_atom = ["server"]
}


server {
    type = "HttpServer"
}

