rm ../cmake-build-debug/src/record/*
rm ../cmake-build-debug/src/data/logs/electric_log*.txt
rm ../cmake-build-debug/src/data/logs/visual_log*.txt
rm ../cmake-build-release/src/record/*
rm ../cmake-build-release/src/data/logs/electric_log*.txt
rm ../cmake-build-release/src/data/logs/visual_log*.txt
rm ../record/*
rm ../data/logs/electric_log*.txt
rm ../data/logs/visual_log*.txt
